#!/bin/bash

cat header.html > index.html
echo '  <header class="container header">' >> index.html
echo '    <h1>לוח מבחנים אינטראקטיבי</h1>' >> index.html
echo '    <p>בחרו את הכיתה שלכם:</p>' >> index.html
echo '  </header>' >> index.html
echo '  <div class="container">' >> index.html

for i in {1..13}
do
  echo '    <p><a href="/yud'$i'/">י'$i'</a><p>' >> index.html
done

echo '  </div>' >> index.html

cat footer.html >> index.html
